name: PlatformIO CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install PlatformIO Core
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Run tests for the native environment
      - name: Run tests
        run: pio test -v -e native

      # Generate coverage report
      - name: Generate Coverage Report
        run: |
          pip install gcovr
          gcovr --root=. --exclude-unreachable-branches --print-summary --xml-pretty --output coverage.xml --html --html-details -o coverage.html

      # Upload coverage as an artifact
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            coverage.xml
            coverage.html